### ISSUE TITLE
Reader turns diacritics into HTML entities or encodes them weirdly

### ISSUE THREAD

**Issue by warren231** [yesean/qbhub-client#10]
**Describe the bug**
In the tossup and bonus reader, some diacritics are rendered as decimal HTML entities and aren't decoded. But in the clue search and on QuizDB, they're fine. Additionally, sometimes the reader doesn't encode characters that have diacritics correctly, even though they are correct in the original QuizDB database.

**To Reproduce**
1. Go to https://qbhub.io/reader/bonus or https://qbhub.io/reader/tossup
2. Go through questions until wacky characters or HTML entities are found.

**Expected behavior**
The diacritics are rendered normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/110417554/190002437-bf92de36-5228-4cdc-9ea9-696ad56d016e.png)
![firefox_gYjwh8XJ5G](https://user-images.githubusercontent.com/110417554/190003520-181a3de2-473b-49ed-95b5-8bd61b45e4b1.png)
![image](https://user-images.githubusercontent.com/110417554/190011262-e282effc-bba9-42a3-88d6-3323b523a5da.png)
![image](https://user-images.githubusercontent.com/110417554/190010002-f923524b-03b1-4b97-bf32-4f389d190ec9.png)
![image](https://user-images.githubusercontent.com/110417554/190007820-0c6ffd1d-dfae-489c-816c-118a9c95d65b.png)
![image](https://user-images.githubusercontent.com/110417554/190009094-27b40064-0921-4132-a4b0-5b9b2a2aa351.png)

![image](https://user-images.githubusercontent.com/110417554/190007648-b968f6bd-1eea-4edb-bc91-48d75f2a2488.png)
![firefox_QGkh2qhHrK](https://user-images.githubusercontent.com/110417554/190007572-97edb756-fe52-415d-abd5-70615b636476.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 104

**Comment by yesean** [comment]
Thanks @warren231 for the detailed report and bringing this to my attention! It seems the diacritics are encoded with HTML entities instead of UTF-8, which React doesn't parse directly. The reason the Clue Generator renders fine is because the text that it operates on *is* UTF-8 encoded, unlike the Question Readers. I checked out QuizDB and they're using HTML entities too, but they're [bypassing React with `dangerouslySetInnerHTML`](https://github.com/UlyssesInvictus/QuizDB/blob/dbe41853ae4a173b881a50988e8b8cdb9834850a/client/src/utilities/Question.js#L47), which I'd prefer not to do this. Plus, we already have an HTML entity decoder for displaying answerlines anways, so it should be a quick fix. I'll push a fix soon.

**Comment by yesean** [comment]
fixed in  7861d429fc001cebae83c68c41158f2e93e9dd74

![image](https://user-images.githubusercontent.com/20366175/190081249-a0991406-1b67-48b0-810f-6fc7eb120d2a.png)
![image](https://user-images.githubusercontent.com/20366175/190081573-19924783-6398-4005-b0ff-c1f25c676ac6.png)
